[project]
name = "pycore"
version = "0.1.0"
description = "xiaoy python core utilities"
readme = "README.md"
requires-python = ">=3.13"

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]

