global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['gateway:8080']
  - job_name: 'aggregator'
    metrics_path: /metrics
    static_configs:
      - targets: ['aggregator:8090']

