services:
  gateway:
    # Overlay for secrets and env files (non-Swarm)
    env_file:
      - .env.local
    environment:
      # Point variables to mounted secret file paths
      - JWT_PUBLIC_KEY=/run/secrets/jwt_pub.pem
      - TLS_CERT_PATH=/run/secrets/tls.crt
      - TLS_KEY_PATH=/run/secrets/tls.key
    volumes:
      # Read-only bind mounts for secrets (provide files under ./.secrets)
      - ./\.secrets/jwt_pub.pem:/run/secrets/jwt_pub.pem:ro
      - ./\.secrets/tls.crt:/run/secrets/tls.crt:ro
      - ./\.secrets/tls.key:/run/secrets/tls.key:ro

# Usage:
#   1) cp .env.example .env.local  # adjust non-sensitive vars
#   2) mkdir -p .secrets && put PEM/CRT/KEY files inside
#   3) docker compose -f docker-compose.yml -f docker-compose.secrets.yml up

