name: buf-breaking
on:
  pull_request:
    paths:
      - 'packages/contracts/**'

jobs:
  breaking-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: bufbuild/buf-setup-action@v1
      - name: Run buf breaking check (base ref if PR)
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: |
          cd packages/contracts
          REF="${BASE_SHA:-main}"
          echo "Using base ref: $REF"
          buf breaking --against ".git#ref=$REF,subdir=packages/contracts" --error-format=github-actions
