name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: ws-gateway deps (pnpm)
        run: pnpm -C services/ws-gateway install

      - name: ws-gateway tests (vitest)
        run: pnpm -C services/ws-gateway vitest run --reporter=verbose

      - name: UI tests (node --test)
        run: node --test apps/ui/test/overlay.test.mjs

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: aggregator-go tests
        run: go test ./services/aggregator-go -run TestHealthzEndpoint -v

