name: pycore-tests
on:
  pull_request:
    paths:
      - 'packages/pycore/**'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install test deps & package (editable)
        run: |
          python -V
          python -m pip install --upgrade pip
          python -m pip install -r packages/pycore/requirements-dev.txt || true
          python -m pip install pytest
          python -m pip install -e packages/pycore
      - name: Run unit tests (pytest)
        run: |
          pytest -q packages/pycore
